### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by ericdude4** [sindresorhus/electron-store#103]
Got the following error from Sentry produced by our production app. Could this be due to some odd permissions that the user has changed on their system?

OS: Windows 10.0.17763
Electron: 8.0.0
electron-store: 3.3.0

```
Error: EPERM: operation not permitted, rename 'C:\Users\mattd\AppData\Roaming\clockk\config.json.2393936311' -> 'C:\Users\mattd\AppData\Roaming\clockk\config.json'
  at Function.writeFileSync [as sync](app:///node_modules/write-file-atomic/index.js:198:8)
  at ElectronStore.set store [as store](app:///node_modules/conf/index.js:267:19)
  at ElectronStore.set(app:///node_modules/conf/index.js:152:14)
  at _.clearArtifacts(app://./js/app.1a7ce22d.js:1:20601)
  at ? (app://./js/chunk-vendors.3f748be6.js:38:5706)
  at ? (app://./js/chunk-vendors.3f748be6.js:38:6751)
  at Array.forEach(<anonymous>)
  at ? (app://./js/chunk-vendors.3f748be6.js:38:6730)
  at _._withCommit(app://./js/chunk-vendors.3f748be6.js:38:8276)
  at _.commit(app://./js/chunk-vendors.3f748be6.js:38:6704)
  at _.commit [as originalCommit](app://./js/chunk-vendors.3f748be6.js:38:3374)
  at EventEmitter.<anonymous>(app://./js/chunk-vendors.3f748be6.js:85:28802)
```

**Comment by sindresorhus** [comment]
This might be a case of https://github.com/npm/write-file-atomic/issues/28.

**Comment by RoderickQiu** [comment]
> 
> 
> This might be a case of [npm/write-file-atomic#28](https://github.com/npm/write-file-atomic/issues/28).

I'm currently having this problem too... The bug doens't always show, but it do occurs from time to time though. According to the issue you mentioned, the problem seems already solved, but it seems that this problem is still with this module with the newest 5.1.x series.

**Comment by RoderickQiu** [comment]
Would the problem vanishes if we could disable all the errors thrown? Though it doesn't seems very safe and dev-friendly.
Anyway, if `electron-store` supports syntax of promise, I think things can be better as this problem is likely to be caused by writing one files at the same time by 2 or more processes.

**Comment by RoderickQiu** [comment]
```javascript
store.set("last-recorded-state", {
       workTime: workTime / 60000,
       restTime: restTime / 60000,
       loop: loop,
       title: title,
       note: note,
       isWorkTimeFocused: store.get("fullscreen-work"),
       isRestTimeFocused: store.get("fullscreen")
});
store.set("last-recorded-method", methodFromStart);
```

The problem occurred again. This is the code that caused bugs this time.

**Comment by lilis7575** [comment]
I am having the same problem.

This problem occurs intermittently.
And, everything happens in window7.

OS: Windows 7 sp1
Electron: 7.0.0
electron-store: 5.1.0

**Comment by RoderickQiu** [comment]
> 
> 
> I am having the same problem.
> 
> This problem occurs intermittently.
> And, everything happens in window7.
> 
> OS: Windows 7 sp1
> Electron: 7.0.0
> electron-store: 5.1.0

Seems that it's a hard-to-solve question... I suggest using trycatches for backporting or prevent 2 processes from modifying the stored content at the same time though it's a bit of uncomfortable to do so and could make your code not so strong...

**Comment by chaveezy** [comment]
Also experiencing this same thing, I initially thought it was due to an antivirus issue, but I realized that I am calling two store.set() at the same time.  I then added a setTimeout(function(){store.set()},1000); and I thought I had it fixed but I still get the same issue.  the timeout was to try and allow for the first store.set() to complete.  Maybe this was the wrong approach?

**Comment by RoderickQiu** [comment]
![image](https://user-images.githubusercontent.com/42290260/78196137-054ba400-74b4-11ea-9777-2d5c1f69cb72.png)

I've once again read the doc of this proj, and this time I found something may be good for you _(and for me, too)_. Haven't tested myself, _though I'm thinking that by using this, your code may need to be complex_.

Anyway, I think for using this lib, **try-catches are necessary** _(and it also seems to be the most convenient and least costly solution to partially fix this?)_ to make your code stronger...

**Comment by mifi** [comment]
A user of my app also just reported the same error https://github.com/mifi/lossless-cut/issues/312

I don’t know what’s causing it. I asked the users some questions about what he was doing. Maybe we need to solve it the same way as the [EXDEV error](https://github.com/sindresorhus/conf/pull/106) by catching and trying again with a normal write?

**Comment by mifi** [comment]
I've been doing some research. I think it boils down to the fact that Windows API for rename is very unstable and depends on a lot of factors like anti-virus, any open file handles, and the moon phase. 

`electron-store` is using `write-file-atomic`, which uses the plain Node.js `fs` api. I think for this to be improved, `write-file-atomic` need to instead use `fs-extra` ([which handles](https://github.com/jprichardson/node-fs-extra/blob/master/lib/move-sync/move-sync.js#L33) the EXDEV issue #106) and it uses `graceful-fs` which [handles the EPERM issue](https://github.com/isaacs/node-graceful-fs#improvements-over-fs-module) with a 1 second retry loop.

One problem is that even with `graceful-fs` [there are still issues with EPERM on windows even though it has 1 second retry logic](https://github.com/isaacs/node-graceful-fs/issues/104)

And I don't think the `write-file-atomic` guys want to use introduce two extra layers of abstraction by adding `fs-extra` dependency, because `write-file-atomic` is being used by a **lot** of packages including `npm` and it might introduce regressions for a lot of people.

So I think either electron-store needs to either:
1. Change [the code that uses write-file-sync](https://github.com/sindresorhus/conf/blob/3ef2da0544e4a7fbe3ffc9ce05ce3fee03a18e2e/index.js#L180) to instead use `fs-extra.rename` and write the file directly with no atomicity guarantee. (or only do so if `platform.os === 'win32'`)
2. include `EPERM` to the catch block if-check along with `EXDEV` to retry with fs.writeFileSync.
3. Write our own write-file-atomic implementation replacement that does the same but instead uses `fs-extra` which better handles these errors.
4. Find another way to guarantee atomicity when writing a config file
5. Keep it as is, but give the developers **huge warnings** in the `electron-store` README about the fact that the `set` function is likely to fail often on Windows and that they need to handle this in their code with try/catch around all set functions

**Comment by mifi** [comment]
Actually as of now, the developer needs to also wrap the the call to `const store = new Store();` with try/catch, because the constructor runs `_watch` which in turn runs `_write` (the first time the app is run)

https://github.com/sindresorhus/conf/blob/410cc144141f1467cc91fe4b16f6b7f42a8afac8/index.js#L199

**Comment by sindresorhus** [comment]
1. Even if only on Windows. This is not a great idea. Before we had atomic writing, we got reports from user having their config corrupted.

I'm fine with either 2 or 3, but I would prefer 3. `write-file-atomic` has consistently been badly maintained and badly coded. I welcome a fork that's better maintained.

**Comment by fabiospampinato** [comment]
> I welcome a fork that's better maintained.

Here we go (hopefully): https://github.com/fabiospampinato/atomically

I'm basically on the same boat and I couldn't find anything better than `write-file-atomic`, so I rewrote it. I'd say `atomically` is probably strictly better than `write-file-atomic`, it handles more errors (including the one mentioned here), it can be 10x faster on synchronous writes and just as safe (I've no idea why in my benchmark it isn't also 10x faster in asynchronous writes), it has way more options (including a way to hide temporary files) etc.

On the code quality I can't comment too much being the author of this one, but at least when putting the async and sync version of the provided functions side by side the implementation is basically identical, in `write-file-atomic` there are a bunch of quirks because this isn't true there too. Unfortunately the test suite is still pretty messy as I inherited the one from `write-file-atomic`, but throwing their tests away didn't feel right and rewriting the entire test suite didn't feel worth it.

Happy to work on any eventual issue you guys can find, I'm going to use this library in an Electron app too so any issue can find I'd be interested in fixing it.

**Comment by jurepetrovic** [comment]
Ok, so we also noticed these problems. I followed @fabiospampinato's advice and integrated atomically into 
electron-store. Now you have an electron-store fork, which uses atomically inside. We started using it and so far no problems on win machines. If anybody needs this, please use it and let me know how it goes. I would really appreciate feedback. Especially from some heavy used electron apps!

https://github.com/jurepetrovic/electron-store-atomically

Thanks, 
Jure

**Comment by sindresorhus** [comment]
PR welcome to switch to this library.

**Comment by ericdude4** [comment]
@jurepetrovic please make a PR, I've been hoping for this fix for months :p

**Comment by jurepetrovic** [comment]
I have made PR #130 , but it requires some more testing for real production. 
Actually the real change is in conf-atomically, where the atomically is actually used. 

I had to change some project data, since I published separate npm package on npmjs for our own use. 

Thanks and Rgds, 
Jure

**Comment by jurepetrovic** [comment]
https://www.npmjs.com/package/electron-store-atomically

If we merge this successfully and it works under windows, I'd be very happy to use this original package!

**Comment by sindresorhus** [comment]
Released: https://github.com/sindresorhus/electron-store/releases/tag/v6.0.0

**Comment by lights0123** [comment]
Side note: this [increases](https://github.com/fabiospampinato/atomically/blob/55d056fcc42633588ed329337108b101cce4e9da/package.json#L36) the minimum supported Node.js version to 12.12.0.

**Comment by fabiospampinato** [comment]
@lights0123 Electron v9.1.0 ships with v12.14.1. Actually you highlighted a bit of an issue with `atomically`, the actual supported version number might be even v8, PR welcome to set the correct one 👍

**Comment by lights0123** [comment]
Yep, I was thinking [this issue](https://github.com/electron/electron/issues/21612) was about Node.js 11 so I was thinking one less.

**Comment by bad2Dbone** [comment]
User told me, that when application starts from .exe file, this error occurs. If the app is started from console, no problem appeared until now.

Maybe this information could be useful to somebody.

**Comment by fabiospampinato** [comment]
@bad2Dbone which version of the library are you using? The one with `write-file-atomic` or the one with `atomically`?

**Comment by bad2Dbone** [comment]
currently the template given for new version: "electron-store-atomically": "^0.0.2",
but Ill try electron-store 6.0.0 and let you know...

**Comment by fabiospampinato** [comment]
@bad2Dbone It sounds like you are using a version with `atomically` already, in that case there isn't too much that can be done, like there are no guarantees that write operations will always succeed, especially in hostile environments like Windows with an aggressive antivirus, you might want to consider switching to asynchronous writes rather than synchronous, as the former have a higher default timeout, or you could just provide `atomically` a higher up timeout is that sounds like a good trade off to you, although currently I don't think `conf` and `electron-store` allow you to pass options to `atomically`.

**Comment by jurepetrovic** [comment]
Ok, so we know 2 things: 
- We could try with higher timeout values in atomically. Will try to follow up on that. 

- Switch to async solution - however conf does not support this, and we would have to do something on our own completely? In this case electron-store cannot be used.  

Am I uderstanding this correctly?

**Comment by fabiospampinato** [comment]
@jurepetrovic Yeah. Switching to async reads and writes is more about them having a higher default timeout in `atomically` really, and you don't always want that, like waiting 5 seconds for a write to succeed at startup or something might not be worth it. There's also [this](https://github.com/fabiospampinato/atomically/issues/1) that could help, I haven't implemented it yet though.

**Comment by jurepetrovic** [comment]
There is another observation which seems important. 

- In development environment, where we use "yarn start" that starts development server and loads localhost:3000 into electron this problem does not happen.

- In packaged environment, where we load static files the problem happens. Any idea what could here be the difference between these two? In both cases, the loaded code is executed in electron's context.  See pic. 

![image](https://user-images.githubusercontent.com/35005863/88288955-c9537d80-ccf4-11ea-8722-28cb5f868e6b.png)


All ideas seriously appreciated ! (beer)

**Comment by fabiospampinato** [comment]
@jurepetrovic There are all sorts of factors that have an impact on this, including if the sun is shining outside or not, and we can't really do much about them, maybe in your case just having all files packages in an asar archive makes the antivirus take longer to scan it and unlock it, even if the part of the archive being scanned is not the one you currently care about.

**Comment by jurepetrovic** [comment]
Ok :) We'll try with this timeout first and then let you know here ;-)

Well - despite everything that is going on here and the number of libs included - I still believe computers are exact 
science.  So there has to be a reason for everything.

**Comment by ericdude4** [comment]
@sindresorhus Can we reopen this issue? I'm still getting the same error reports from client machines.

**Comment by bad2Dbone** [comment]
We ar now using https://github.com/jurepetrovic/electron-store-atomically which has higher timeout for writing. There were no problems detected so far.

**Comment by ericdude4** [comment]
@bad2Dbone Is it a drop-in replacement for electron-store?

**Comment by jurepetrovic** [comment]
Yes, you can replace it as-is. But only thing changed is the timeout (from 100ms to 500ms) that is given to the operating system for finishing the write operation. In other words, we allow the operating system  more time to do the write operation before aborting.

**Comment by bei-yang** [comment]
The version number I used is 6.0.1 and I still have this problem

**Comment by bei-yang** [comment]
I still have this problem
 
 electron-store:6.0.1
 electron:8.5.2

**Comment by bei-yang** [comment]
> @sindresorhus Can we reopen this issue? I'm still getting the same error reports from client machines.

Does my brother still have this problem?

**Comment by fabiospampinato** [comment]
IMHO pretty much the only lever that can be pulled is giving `atomically` more time to write stuff by raising the timeout and/or switching to async writing. If there's anything else that can be tried to fix this I'm no aware of this.

**Comment by Brouilles** [comment]
I have this problem in production. Not everytime, but often enough to be disturbing.
electron-store: 8.0.1
electron: 8.0.1

**Comment by PDKSophia** [comment]
I have the same problem ...
electron-store: 8.1.0
electron: 22.0.1

**Comment by liees** [comment]
> I have the same problem ... electron-store: 8.1.0 electron: 22.0.1

这个问题你已经解决了嘛？
