### ISSUE TITLE
Cannot find module 'conf'

### ISSUE THREAD

**Issue by ifzm** [sindresorhus/electron-store#241]
I use electron-builder to build the package successfully, but this error appears when I run it, what could be the reason? thanks )

**Comment by ifzm** [comment]
![image](https://user-images.githubusercontent.com/12740295/204159330-8c55c11f-42aa-4dff-a4de-47999711c64c.png)

**Comment by irg1008** [comment]
Why did you closed it and not provide the solution?

**Comment by SSmJaE** [comment]
## Reason

The readme claims

>Initializer to set up the required ipc communication channels for the module when a Store instance is not created in the main process and you are creating a Store instance in the Electron renderer process only.

But I believed it might be working  only under the premise that `nodeIntergration` is `false`

Since `electron-store` is merely a wrapper for `conf` to make it appropriate for electron, `initRenderer` may employ some tricks to make it work properly (possibly only when `nodeIntergration` is `false`)

So when `nodeIntergration` is `true`, `initRenderer` results in the error `Cannot find module "conf"`

## Solution

Because we have turn `nodeIntergration` on, there is no longer a requirement for `electron-store`, we can utilize `conf` directly in "renderer process", and "main process" doesn't require any specific imports

**Comment by Yeuoly** [comment]
you should use
```ts
import electronStore from 'electron-store'
```
 instead of using
```ts
const electronStore = require('electron-store)
```

**Comment by ifzm** [comment]
> Why did you closed it and not provide the solution?

I have this problem because I use it in the renderer, it should be related to the post-build, I later changed to ipc no problem @irg1008
