### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by wmelton** [sindresorhus/electron-store#248]
Curious what the appetite is to add helper functions that alias existing functions to match the official Web Storage API? 

This feels kind of clunky if you're running a web app and electron app on the same code base: 

```js
const remove = async (key: string): Promise<void> => {
  if (electron) {
    return electronStorage.delete(key)
  }
  return windowStorage.removeItem(key)
}
```

**Comment by sindresorhus** [comment]
It doesn't really make sense to me. The API's are very different even though they have three similar methods. I also don't think it's a very common use-case. This package has existed for years and no one else has requested this.

It should be simple to subclass the Store class and add such methods yourself and then you can just import your subclass instead of `electron-store` where you need it.
