### ISSUE TITLE
Doesnt work with Webpack

### ISSUE THREAD

**Issue by bradennapier** [sindresorhus/electron-store#34]
You close and lock issues but they arent resolved - this doesnt work with webpack.  Locking the issue so no one can post in it and provide solutions only makes the issue far worse.  Asking to just go ask in webpack doesnt help solve the problem when people run into it and is EXTREMELY upsetting and annoying.  If you didn't lock it to purposefully make it hard to fix this issue then perhaps people would have provided more solutions to find one that works for everyone...

**Comment by sindresorhus** [comment]
I close and lock them because it's not something that will or should be fixed here. This module works perfectly in Electron. It's not my responsibility to support every unrelated tool out there.

If you want to see this fixed, encourage Webpack to improve their docs and compatibility with the Node.js ecosystem instead. Otherwise, you're just part of the problem.

Relevant tweet: https://twitter.com/sindresorhus/status/932783602026258433
